spring:
  application:
    name: spring-plus-project

  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/springplusproject?rewriteBatchedStatements=true}
    username: ${MYSQL_USERNAME:testuser}
    password: ${MYSQL_PASSWORD:testpass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
    open-in-view: false

  batch.job.enabled: false

jwt:
  secret: ${JWT_SECRET:default-secret}